kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-production
  template:
    metadata:
      labels:
        app: backend-production
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup mongodb-service.production.svc.cluster.local; do echo waiting for mongodb; sleep 2; done;']
      containers:
        - name: backend-app
          image: sujaldevops1/task-manager-backend:v2
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: MONGO_HOST
              value: "mongodb-service.production.svc.cluster.local"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-password
            - name: MONGO_DB
              value: "taskmanager"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20         
