kind: Service
apiVersion: v1
metadata:
  name: backend-service
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: backend-production
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 80

